### ISSUE TITLE
请问一下

### ISSUE THREAD

**Issue by Composure17** [mochazi/AutoFishing#3]
编译后提示没有找到游戏窗口
![image](https://github.com/mochazi/AutoFishing/assets/38198174/de410583-aa86-49ff-a461-851a69c1961d)

**Comment by Composure17** [comment]
加上版本号的话 能看到他动但看不到他点下去 只是鼠标移动 最后提示 没有匹配目标, 请确保游戏窗口没有脱离显示器屏幕

**Comment by mochazi** [comment]
@Composure17 
[检查游戏进程](https://github.com/mochazi/AutoFishing/blob/d7b333e5c90eea27b87c0d8985d5f735ddee54fd/main.py#L895)

港服游戏进程`Tales Runner`
国服游戏进程`Tales Runner ver.`

- 点不下去的原因
国服用了SP反作弊系统，限制了鼠标输入功能，键盘输入好像可以
港服用了小蓝熊系统，没什么限制

**Comment by Composure17** [comment]
那就是说 国服没办法能自动钓鱼了吗

> @Composure17 [检查游戏进程](https://github.com/mochazi/AutoFishing/blob/d7b333e5c90eea27b87c0d8985d5f735ddee54fd/main.py#L895)

**Comment by mochazi** [comment]
> 那就是说 国服没办法能自动钓鱼了吗
> 
> > @Composure17 [检查游戏进程](https://github.com/mochazi/AutoFishing/blob/d7b333e5c90eea27b87c0d8985d5f735ddee54fd/main.py#L895)

是的，`pywinauto`和`pygetwindow`都点不下去，但可以鼠标移动

**Comment by Composure17** [comment]
有可能过SP检测么

**Comment by mochazi** [comment]
> 可能有过SP检测么

目前没找到python库能过，你找到可以告诉我

**Comment by Composure17** [comment]
别的语言能过？ 
python没找到 要往什么方向找 0 0

**Comment by mochazi** [comment]
> 别的语言能过？ python没找到 要往什么方向找 0 0

跟语言没什么关系，模拟鼠标键盘调用了`Win32 API`
而`pywinauto`和`pygetwindow`已经封装了`Win32 API`

用别的语言差别并不大

**Comment by Composure17** [comment]
> > 别的语言能过？ python没找到 要往什么方向找 0 0
> 
> 跟语言没什么关系，模拟鼠标键盘调用了`Win32 API` 而`pywinauto`和`pygetwindow`已经封装了`Win32 API`
> 
> 用别的语言差别并不大

好像外面传者一个版本是你的 然后能用 还能挂活动的 钓鱼也没问题

**Comment by mochazi** [comment]
> > > 其他语言能过吗？ python没找到要往什么方向找 0 0
> > 
> > 
> > 跟语言没有关系，模拟键盘调用了`Win32 API`并且`pywinauto`已经`pygetwindow`封装了`Win32 API`
> > 用其他语言差别并不大
> 
> 希望外部传者的一个版本是你的然后能够使用挂起活动的钓鱼也没有问题

或许指的是[AutoRunMap](https://github.com/mochazi/AutoRunMap)自动跑图

刚开始为了`极速拼图`设计的

![image](https://github.com/mochazi/AutoFishing/assets/54659396/fa9b5db4-13fa-41c7-b55e-fd57aecc7e18)

后来玩家反馈，穿`抗电装`跑隧道更好一些

![image](https://github.com/mochazi/AutoFishing/assets/54659396/f534987e-45cb-4920-b484-1741883d328e)

这个程序需要你手动进入房间
如果你想跑活动图，可以在[此处](https://github.com/mochazi/AutoRunMap/blob/v1.2/main.py#L1104)增加点击事件自动进入房间

**Comment by Composure17** [comment]
> > > > 其他语言能过吗？ python没找到要往什么方向找 0 0
> > > 
> > > 
> > > 跟语言没有关系，模拟键盘调用了`Win32 API`并且`pywinauto`已经`pygetwindow`封装了`Win32 API`
> > > 用其他语言差别并不大
> > 
> > 
> > 希望外部传者的一个版本是你的然后能够使用挂起活动的钓鱼也没有问题
> 
> 或许指的是[AutoRunMap](https://github.com/mochazi/AutoRunMap)自动跑图
> 
> 刚开始为了`极速拼图`设计的
> 
> ![image](https://user-images.githubusercontent.com/54659396/269565611-fa9b5db4-13fa-41c7-b55e-fd57aecc7e18.png)
> 
> 后来玩家反馈，穿`抗电装`跑隧道更好一些
> 
> ![image](https://user-images.githubusercontent.com/54659396/269565016-f534987e-45cb-4920-b484-1741883d328e.png)
> 
> 这个程序需要你手动进入房间 如果你想跑活动图，可以在[此处](https://github.com/mochazi/AutoRunMap/blob/v1.2/main.py#L1104)增加点击事件自动进入房间

好像是自动开始也能点击 钓鱼那个他们也弄出来了 我看名字就跟你项目名字一样 ，感觉就是不知道他们怎么做到能自动钓鱼

**Comment by mochazi** [comment]
> > > > > 其他语言能过吗？ python没找到要往什么方向找 0 0
> > > > 
> > > > 
> > > > 跟语言没有关系，模拟键盘调用了`Win32 API`并且`pywinauto`已经`pygetwindow`封装了`Win32 API`
> > > > 用其他语言差别并不大
> > > 
> > > 
> > > 希望外部传者的一个版本是你的然后能够使用挂起活动的钓鱼也没有问题
> > 
> > 
> > 或许指的是[AutoRunMap](https://github.com/mochazi/AutoRunMap)自动跑图
> > 刚开始为了`极速拼图`设计的
> > ![image](https://user-images.githubusercontent.com/54659396/269565611-fa9b5db4-13fa-41c7-b55e-fd57aecc7e18.png)
> > 后来玩家反馈，穿`抗电装`跑隧道更好一些
> > ![image](https://user-images.githubusercontent.com/54659396/269565016-f534987e-45cb-4920-b484-1741883d328e.png)
> > 这个程序需要你手动进入房间 如果你想跑活动图，可以在[此处](https://github.com/mochazi/AutoRunMap/blob/v1.2/main.py#L1104)增加点击事件自动进入房间
> 
> 好像是自动开始也能点击 钓鱼那个他们也弄出来了 我看名字就跟你项目名字一样 ，感觉就是不知道他们怎么做到能自动钓鱼

[AutoRunMap发行版](https://github.com/mochazi/AutoRunMap/releases)自动开始、准备、点击验证码都是可以的

**Comment by Composure17** [comment]
pydirectinput 好像可以按的了诶 能识别图3的学院占领有可能实现么 或者图4的跑到经验区

**Comment by mochazi** [comment]
> pydirectinput 好像可以按的了诶 能识别图3的学院占领有可能实现么 或者图4的跑到经验区

程序的按键输入是[pydirectinput](https://github.com/mochazi/AutoRunMap/blob/1c328997913f32b5464f9c409e8637403b89368b/main.py#L1343)并没有修改

**Comment by Composure17** [comment]
https://blog.csdn.net/Salvator_/article/details/131881423

**Comment by Composure17** [comment]
是这个问题么

**Comment by mochazi** [comment]
> 是这个问题么

应该不是
